"""rename department

Revision ID: 680e0547deee
Revises: 2717e4ffed2d
Create Date: 2025-04-02 09:41:26.759342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680e0547deee'
down_revision = '2717e4ffed2d'
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.rename_table('department', 'departments',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('name', sa.String(), nullable=False),
#     sa.Column('address', sa.String(), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.drop_table('department')
#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.rename_table('departments', 'department'
#     sa.Column('id', sa.INTEGER(), nullable=False),
#     sa.Column('name', sa.VARCHAR(), nullable=False),
#     sa.Column('address', sa.VARCHAR(), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.drop_table('departments')
#     # ### end Alembic commands ###

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###